### ISSUE TITLE
Cant flash beacause I get  an java.lang.NullPointerException

### ISSUE THREAD

**Issue by DerPicknicker** [SpenceKonde/jtag2updi#4]
Hello, 

I try to flash an Attiny 404 .. But i get these Errors and I cant find an solution. I tested with two Systems Windows and macOS .. I get the Error on both systems and cant figure out where it comes from. 

I used an Arduino Nano as an Programmer and the Sketch (jtag2updi) is already uploaded. If you need more information, just comment. 

java.lang.NullPointerException
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingProgrammer(SerialUploader.java:295)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:90)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2055)
	at java.lang.Thread.run(Thread.java:748)
EDIT 1: My Settings: 

![Screenshot 2020-12-11 212038](https://user-images.githubusercontent.com/64746593/101951114-bf281200-3bf6-11eb-8f70-892a4370f1d9.png)

**Comment by Dlloydev** [comment]
Just some thoughts...

If the target is on an SOIC to DIP adapter, make sure to have a 0.1µF bypass cap installed as close as possible to the power pins. Try a series resistance (270 ohm to 2.2K) in the UPDI signal (not 4.7K) and keep the leads as short as possible.

Note that if you don't have a HV Programmer and the UPDI pin is programmed with any other selection (Reset or GPIO) then this will brick the chip. I've read that others have recovered older iteration MCUs of this type by breifly touching 12V to the PA0 pin, then successfully re-programming.

When you say "flash", do you mean "Upload Using Programmer" or "Burn Bootloader"? Note that some configuration changes require you to "Burn Bootloader" first.
