### ISSUE TITLE
Uploading error using jtag2updi

### ISSUE THREAD

**Issue by Jinhoonk** [SpenceKonde/jtag2updi#7]
Hi, 

Thank you for sharing such good resources! 

I am trying to program ATtiny806 using Arduino Nano. 

When I tried, I faced an error while uploading any source codes. 

Here is the message. 

An error occurred while uploading the sketch

avrdude: ser_open(): can't open device "\\.\COM2": Access is denied.

An error occurred while uploading the sketch

Exception in thread "Thread-23" java.util.ConcurrentModificationException

	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)

	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)

	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)

	at cc.arduino.contributions.libraries.LibrariesIndexer.rescanLibraries(LibrariesIndexer.java:169)

	at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:681)

	at processing.app.Base.onBoardOrPortChange(Base.java:1345)

	at processing.app.Editor$UploadHandler.run(Editor.java:2091)

	at java.lang.Thread.run(Thread.java:748)

Is anyone who faced same problems? Could you tell me how to address this issue?

Thank you so much!

**Comment by 1larity** [comment]
A common problem with USB serial ports on windows 10 (not specific to this project, Arduino or even MCU family), the only way I've found to fix it temporarily is to unplug the USB , plug it in and hit the upload button in Arduino or platformIO. you may have to repeat this several times before you get the right timing to defeat windows security.

**Comment by SpenceKonde** [comment]
Avrdude: ser_open(): can't open device "\.\COM2": Access is denied.

On windows, that's what it shows you f you've selected a seraal portthat is in use or not not fully functionals. Ususally it's something like some other program being left with that window open. I've also seen it afer and unclean attempt top use the port Like when you start uploading and the it briefly short against some metal object, it disappears from USB for a second the wtrite failsl  - I've seen the ext attemp fail with that error . 

Upliad err0rs arre generally nor very informative and give little directio nfor debugging to follow. available when you try to write to it. Sto

**Comment by SpenceKonde** [comment]
Maintenance (by me at least) is done. Finished. Irt is a legacy programming option that is not the subject ongoing development no planned futurre development.

Users are advised to transition to SerialUPDI.
